version: "3.8"

services:
  db:
    image: postgres:15
    container_name: finplanpro-db
    environment:
      POSTGRES_DB: finplanpro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # Changed port mapping
    volumes:
      - finplanpro_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: finplanpro-app
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      DATABASE_URL: jdbc:postgresql://db:5432/finplanpro
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy

volumes:
  finplanpro_postgres_data:


