version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: finplanpro_postgres
    restart: always
    environment:
      POSTGRES_USER: finuser
      POSTGRES_PASSWORD: finpass123
      POSTGRES_DB: finplanpro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: finplanpro_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finpro.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - finnet

networks:
  finnet:

volumes:
  postgres_data:
