[build]
builder = "dockerfile"

[deploy]
startCommand = "java -Xmx400m -Xms200m -jar app.jar"
healthcheckPath = "/login"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
